pipeline {
    parameters {
        choice(name: 'terraformAction', choices: ['apply', 'destroy'], description: 'Choose the Terraform action to perform')
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'terraforn', url: 'https://github.com/ManojKRISHNAPPA/career-devops-micro.git'
            }
        }

        stage('Plan') {
            steps {
                sh ''' 
                    cd s3bucket
                    terraform init
                    terraform plan -out=tfplan
                    terraform show -no-color tfplan > tfplan.txt
                '''
            }
        }

        stage('Approval') {
            steps {
                script {
                    def plan = readFile 's3bucket/tfplan.txt'
                    input message: "Do you want to proceed with the Terraform action?",
                          parameters: [
                              text(name: 'Plan', description: 'Please review the code/plan once', defaultValue: plan)
                          ]
                }
            }
        }

        stage('Create/Destroy') {
            when {
                expression {
                    return params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                }
            }
            steps {
                script {
                    // Make sure you're in the right directory
                    dir('s3bucket') {
                        if (params.terraformAction == 'apply') {
                            sh 'terraform apply -input=false tfplan'
                        } else if (params.terraformAction == 'destroy') {
                            sh 'terraform destroy -auto-approve'
                        }
                    }
                }
            }
        }
    }
}